change some small stuff

diff --git a/.s2i/pre_assemble b/.s2i/pre_assemble
--- a/.s2i/pre_assemble
+++ b/.s2i/pre_assemble
@@ -1,8 +1,12 @@
 #!/bin/bash
+set -xe
 
 if [[ -n "${OPENPROJECT_MANAGED_REPOS}" ]]; then
     ln -snf /tmp/src/config/configuration.yml /opt/app-root/etc/configuration.yml
 fi
+
+# don't understand why ~> 2.4.1 fails if we have 2.4.0?
+sed -i /^ruby/d /tmp/src/Gemfile
 # run bundle to generate lockfile or else build
 # will fail when bundle is called with --deployment
 # this is mainly because plugins are set with
@@ -12,3 +16,4 @@ cd /tmp/src && bundle --path bundle
 # a conflict with /tmp/src/.bundle/config
 # when copying in assemble script
 rm -rf /opt/app-root/src/.bundle
+cd /tmp/src/frontend && npm install
